import 'dart:convert';
import 'package:http/http.dart' as http;
import '../../common/config.dart';

class ServiceService {
  static String get baseUrl => AppConfig.baseApiUrl;

  // Headers communs
  static Map<String, String> get headers => {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
  };

  // Obtenir tous les services
  static Future<List<Service>> getAllServices() async {
    try {
      print('🌐 Tentative de connexion à: \$baseUrl/services');
      print('📡 Headers: \$headers');

      final response = await http.get(
        Uri.parse('\$baseUrl/services'),
        headers: headers,
      );

      print('📊 Status Code: \${response.statusCode}');
      print('📄 Response Headers: \${response.headers}');
      print(
        '📝 Response Body (first 200 chars): \${response.body.length > 200 ? response.body.substring(0, 200) + "..." : response.body}',
      );

      if (response.statusCode == 200) {
        List<dynamic> jsonData = json.decode(response.body);
        List<Service> services = jsonData
            .map((json) => Service.fromJson(json))
            .toList();
        print('✅ \${services.length} services chargés avec succès');
        return services;
      } else {
        print('❌ Erreur API: \${response.statusCode} - \${response.body}');
        // Retourner une liste par défaut en cas d'erreur
        return _getDefaultServices();
      }
    } catch (e) {
      print('Erreur API getAllServices: \$e');
      // Retourner une liste par défaut en cas d'erreur
      return _getDefaultServices();
    }
  }

  // Liste par défaut des services (basée sur la vraie base de données PostgreSQL)
  static List<Service> _getDefaultServices() {
    final now = DateTime.now();
    return [
      Service(
        id: 1,
        name: 'Plombier(e)',
        description: 'Installation et réparation de plomberie',
        icon: 'plumbing',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 2,
        name: 'Électricien(e)',
        description: 'Installation et maintenance électrique',
        icon: 'electrical_services',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 3,
        name: 'Maçon(ne)',
        description: 'Travaux de maçonnerie et construction',
        icon: 'construction',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 4,
        name: 'Peintre en bâtiment',
        description: 'Peinture et décoration de bâtiments',
        icon: 'format_paint',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 5,
        name: 'Carreleur(e)',
        description: 'Pose et réparation de carrelage',
        icon: 'grid_view',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 6,
        name: 'Menuisier(e)',
        description: 'Travaux de menuiserie et ébénisterie',
        icon: 'carpenter',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 7,
        name: 'Vitrier(e)',
        description: 'Installation et réparation de vitres',
        icon: 'window',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 8,
        name: 'Plaquiste(e)',
        description: 'Pose de plaques de plâtre',
        icon: 'view_in_ar',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 9,
        name: 'Terrassier(e)',
        description: 'Travaux de terrassement',
        icon: 'landscape',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 10,
        name: 'Couvreur(e)',
        description: 'Travaux de couverture et toiture',
        icon: 'roofing',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 11,
        name: 'Charpentier(e)',
        description: 'Travaux de charpente',
        icon: 'forest',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 12,
        name: 'Serrurier(e)',
        description: 'Installation et réparation de serrures',
        icon: 'lock',
        category: 'BÂTIMENT & CONSTRUCTION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 13,
        name: 'Frigoriste (climatiseur)',
        description: 'Installation et réparation de climatisation',
        icon: 'ac_unit',
        category: 'FROID & CLIMATISATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 14,
        name: 'Installateur/Reparateur de climatisation',
        description: 'Installation et maintenance de systèmes de climatisation',
        icon: 'air',
        category: 'FROID & CLIMATISATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 15,
        name: 'Chauffagiste(e)',
        description: 'Installation et réparation de chauffage',
        icon: 'local_fire_department',
        category: 'FROID & CLIMATISATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 16,
        name: 'Technicien CVC',
        description: 'Technicien en chauffage, ventilation et climatisation',
        icon: 'thermostat',
        category: 'FROID & CLIMATISATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 17,
        name: 'Mécanicien automobile',
        description: 'Réparation et maintenance automobile',
        icon: 'car_repair',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 18,
        name: 'Mécanicien moto',
        description: 'Réparation et maintenance de motos',
        icon: 'motorcycle',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 19,
        name: 'Carrossier',
        description: 'Réparation de carrosserie automobile',
        icon: 'car_crash',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 20,
        name: 'Peintre automobile',
        description: 'Peinture et retouche automobile',
        icon: 'color_lens',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 21,
        name: 'Soudeur(e)',
        description: 'Travaux de soudure',
        icon: 'whatshot',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 22,
        name: 'Chaudronnier(e)',
        description: 'Travaux de chaudronnerie',
        icon: 'engineering',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 23,
        name: 'Mécanicien vélo',
        description: 'Réparation et maintenance de vélos',
        icon: 'pedal_bike',
        category: 'MÉCANIQUE & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 24,
        name: 'Laveur de voitures',
        description: 'Lavage et nettoyage de véhicules',
        icon: 'local_car_wash',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 25,
        name: 'Agent d\'entretien',
        description: 'Entretien et maintenance générale',
        icon: 'cleaning_services',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 26,
        name: 'Femme de ménage',
        description: 'Services de ménage à domicile',
        icon: 'home_repair_service',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 27,
        name: 'Agent de nettoyage',
        description: 'Services de nettoyage professionnel',
        icon: 'cleaning_services',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 28,
        name: 'Éboueur',
        description: 'Collecte et gestion des déchets',
        icon: 'delete',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 29,
        name: 'Nettoyage industriel',
        description: 'Nettoyage industriel et commercial',
        icon: 'factory',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 30,
        name: 'Repassage',
        description: 'Services de repassage',
        icon: 'iron',
        category: 'ENTRETIEN & PROPRETÉ',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 31,
        name: 'Cuisinier/Aide-cuisinier',
        description: 'Préparation de repas et cuisine',
        icon: 'restaurant',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 32,
        name: 'Pâtissier(e)',
        description: 'Préparation de pâtisseries et desserts',
        icon: 'cake',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 33,
        name: 'Boulanger(e)',
        description: 'Préparation de pain et viennoiseries',
        icon: 'bakery_dining',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 34,
        name: 'Boucher(e)',
        description: 'Découpe et préparation de viandes',
        icon: 'kitchen',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 35,
        name: 'Traiteur(e)',
        description: 'Services de traiteur et événements',
        icon: 'room_service',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 36,
        name: 'Serveur(e)',
        description: 'Service en salle et accueil client',
        icon: 'restaurant_menu',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 37,
        name: 'Barman(e)',
        description: 'Préparation de boissons et cocktails',
        icon: 'local_bar',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 38,
        name: 'Sommelier(e)',
        description: 'Conseil en vins et boissons',
        icon: 'wine_bar',
        category: 'RESTAURATION & ALIMENTAIRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 39,
        name: 'Réceptionniste(e)',
        description: 'Accueil et service client',
        icon: 'desk',
        category: 'SERVICE & HÔTELLERIE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 40,
        name: 'Concierge(e)',
        description: 'Services de conciergerie',
        icon: 'support_agent',
        category: 'SERVICE & HÔTELLERIE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 41,
        name: 'Chauffeur(e)',
        description: 'Services de transport et conduite',
        icon: 'drive_eta',
        category: 'SERVICE & HÔTELLERIE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 42,
        name: 'Guide touristique(e)',
        description: 'Accompagnement et guidage touristique',
        icon: 'tour',
        category: 'SERVICE & HÔTELLERIE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 43,
        name: 'Coiffeur(se)',
        description: 'Coupe et coiffage de cheveux',
        icon: 'content_cut',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 44,
        name: 'Maquilleuse',
        description: 'Services de maquillage',
        icon: 'face',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 45,
        name: 'Manucure',
        description: 'Soins et embellissement des ongles',
        icon: 'self_improvement',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 46,
        name: 'Massage',
        description: 'Services de massage et relaxation',
        icon: 'spa',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 47,
        name: 'Pédicure',
        description: 'Soins des pieds et ongles',
        icon: 'self_improvement',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 48,
        name: 'Esthéticienne',
        description: 'Soins esthétiques et beauté',
        icon: 'face_retouching_natural',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 49,
        name: 'Barbier(e)',
        description: 'Coupe et soins masculins',
        icon: 'content_cut',
        category: 'BEAUTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 50,
        name: 'Jardinier(e)',
        description: 'Entretien et aménagement de jardins',
        icon: 'grass',
        category: 'SERVICES À DOMICILE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 51,
        name: 'Garde d\'enfants(e)',
        description: 'Garde et surveillance d\'enfants',
        icon: 'child_care',
        category: 'SERVICES À DOMICILE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 52,
        name: 'Laveur de linge(e)',
        description: 'Lavage et entretien du linge',
        icon: 'local_laundry_service',
        category: 'SERVICES À DOMICILE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 53,
        name: 'Nounou',
        description: 'Garde d\'enfants et baby-sitting',
        icon: 'baby_changing_station',
        category: 'SERVICES À DOMICILE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 54,
        name: 'Aide-ménagère',
        description: 'Aide aux tâches ménagères',
        icon: 'home_repair_service',
        category: 'SERVICES À DOMICILE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 55,
        name: 'Tuteur(e)',
        description: 'Soutien scolaire et cours particuliers',
        icon: 'school',
        category: 'SERVICES À DOMICILE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 56,
        name: 'Réparateur d\'électroménager(e)',
        description: 'Réparation d\'appareils électroménagers',
        icon: 'build_circle',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 57,
        name: 'Réparateur de téléphone(e)',
        description: 'Réparation de téléphones mobiles',
        icon: 'phone_android',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 58,
        name: 'Réparateur d\'ordinateur(e)',
        description: 'Réparation et maintenance informatique',
        icon: 'computer',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 59,
        name: 'Réparateur de vélo(e)',
        description: 'Réparation et entretien de vélos',
        icon: 'pedal_bike',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 60,
        name: 'Réparateur de moto(e)',
        description: 'Réparation et maintenance de motos',
        icon: 'motorcycle',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 61,
        name: 'Réparateur TV(e)',
        description: 'Réparation de téléviseurs',
        icon: 'tv',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 62,
        name: 'Réparateur lave-linge(e)',
        description: 'Réparation de machines à laver',
        icon: 'local_laundry_service',
        category: 'RÉPARATION & MAINTENANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 63,
        name: 'Technicien informatique(e)',
        description: 'Support et maintenance informatique',
        icon: 'computer',
        category: 'TECHNOLOGIE & COMMUNICATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 64,
        name: 'Installateur d\'antenne(e)',
        description: 'Installation d\'antennes et paraboles',
        icon: 'signal_cellular_alt',
        category: 'TECHNOLOGIE & COMMUNICATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 65,
        name: 'Technicien télécom(e)',
        description: 'Installation et maintenance télécoms',
        icon: 'signal_cellular_alt',
        category: 'TECHNOLOGIE & COMMUNICATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 66,
        name: 'Graphiste(e)',
        description: 'Création graphique et design',
        icon: 'design_services',
        category: 'TECHNOLOGIE & COMMUNICATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 67,
        name: 'Photographe(e)',
        description: 'Services de photographie',
        icon: 'camera_alt',
        category: 'TECHNOLOGIE & COMMUNICATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 68,
        name: 'Professeur particulier(e)',
        description: 'Cours particuliers et soutien scolaire',
        icon: 'school',
        category: 'ÉDUCATION & FORMATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 69,
        name: 'Formateur(e)',
        description: 'Formation professionnelle',
        icon: 'person_add_alt_1',
        category: 'ÉDUCATION & FORMATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 70,
        name: 'Coach(e)',
        description: 'Coaching personnel et professionnel',
        icon: 'sports_motorsports',
        category: 'ÉDUCATION & FORMATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 71,
        name: 'Traducteur(e)',
        description: 'Services de traduction',
        icon: 'translate',
        category: 'ÉDUCATION & FORMATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 72,
        name: 'Infirmier à domicile(e)',
        description: 'Soins infirmiers à domicile',
        icon: 'medical_services',
        category: 'SANTÉ & BIEN-ÊTRE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 73,
        name: 'Couturier(e)',
        description: 'Couture et retouches',
        icon: 'content_cut',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 74,
        name: 'Cordonnier(e)',
        description: 'Réparation et fabrication de chaussures',
        icon: 'shopping_bag',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 75,
        name: 'Bijoutier(e)',
        description: 'Fabrication et réparation de bijoux',
        icon: 'diamond',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 76,
        name: 'Sculpteur(e)',
        description: 'Sculpture et création artistique',
        icon: 'palette',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 77,
        name: 'Peintre artiste(e)',
        description: 'Peinture artistique et décoration',
        icon: 'palette',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 78,
        name: 'Tapissier(e)',
        description: 'Tapisserie et rembourrage',
        icon: 'chair',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 79,
        name: 'Ébéniste(e)',
        description: 'Fabrication et restauration de meubles',
        icon: 'carpenter',
        category: 'ARTISANAT & CRÉATION',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 80,
        name: 'Agent de sécurité(e)',
        description: 'Services de sécurité et surveillance',
        icon: 'security',
        category: 'SÉCURITÉ & SURVEILLANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 81,
        name: 'Garde du corps(e)',
        description: 'Protection et sécurité personnelle',
        icon: 'person_pin',
        category: 'SÉCURITÉ & SURVEILLANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 82,
        name: 'Surveillant(e)',
        description: 'Surveillance et monitoring',
        icon: 'visibility',
        category: 'SÉCURITÉ & SURVEILLANCE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 83,
        name: 'Agriculteur(e)',
        description: 'Travaux agricoles et culture',
        icon: 'agriculture',
        category: 'AGRICULTURE & ÉLEVAGE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 84,
        name: 'Éleveur(e)',
        description: 'Élevage et soins d\'animaux',
        icon: 'pets',
        category: 'AGRICULTURE & ÉLEVAGE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 85,
        name: 'Vétérinaire(e)',
        description: 'Soins vétérinaires',
        icon: 'medical_services',
        category: 'AGRICULTURE & ÉLEVAGE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 86,
        name: 'Ouvrier agricole(e)',
        description: 'Travaux agricoles et manutention',
        icon: 'agriculture',
        category: 'AGRICULTURE & ÉLEVAGE',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 87,
        name: 'DJ',
        description: 'Animation musicale et DJ',
        icon: 'music_note',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 88,
        name: 'Musicien(ne)',
        description: 'Prestation musicale',
        icon: 'music_note',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 89,
        name: 'Animateur(e)',
        description: 'Animation et divertissement',
        icon: 'mic',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 90,
        name: 'Organisateur d\'événements(e)',
        description: 'Organisation d\'événements',
        icon: 'event',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 91,
        name: 'Décorateur(e)',
        description: 'Décoration et aménagement',
        icon: 'home_repair_service',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 92,
        name: 'Comédien(ne)',
        description: 'Prestation théâtrale et artistique',
        icon: 'theater_comedy',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
      Service(
        id: 93,
        name: 'Danseur(e)',
        description: 'Prestation de danse',
        icon: 'music_note',
        category: 'DIVERTISSEMENT & ÉVÉNEMENTIEL',
        isActive: true,
        createdAt: now,
      ),
    ];
  }
}

// Modèle Service
class Service {
  final int id;
  final String name;
  final String description;
  final String icon;
  final String category;
  final String? imageUrl;
  final bool isActive;
  final DateTime createdAt;
  final DateTime? updatedAt;

  Service({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.category,
    this.imageUrl,
    required this.isActive,
    required this.createdAt,
    this.updatedAt,
  });

  factory Service.fromJson(Map<String, dynamic> json) {
    return Service(
      id: json['id'],
      name: json['name'],
      description: json['description'] ?? '',
      icon: json['icon'] ?? '🔧',
      category: json['category'] ?? 'Autre',
      imageUrl: json['imageUrl'],
      isActive: json['isActive'] ?? true,
      createdAt: DateTime.parse(
        json['createdAt'] ?? DateTime.now().toIso8601String(),
      ),
      updatedAt: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'])
          : null,
    );
  }
}